### ISSUE TITLE
sst files ever growing in size

### ISSUE THREAD

**Issue by wellington-felix-movile** [pcmind/leveldb#11]
Hi! I ran the following test using both your fork of leveldb as well as dain's original repo and they seem to yield the same result.
```kotlin
fun main() {
    val db = Iq80DBFactory.factory.open(File("storage-test"), Options())

    repeat(100_000) {
        db.put(it.toString().toByteArray(), Random.nextBytes(1000))
        println("Inserted id=$it")
    }
    repeat(100_000) {
        try {
            db.delete(it.toString().toByteArray())
            println("Deleted id=$it")
        } catch (e: Exception) {
            println("[ERROR] error deleting key=$it. ex: $e")
        }
    }
 
    db?.close()
}
```
Running the code above it seems that leveldb is never capable of reclaiming disk space even though all entries are deleted.
Watching the files in the `storage-test` folder with `watch -n 0.1 ls -lhv . ` I can see that very little space is reclaimed and in the end the folder is ~100MB in size and has about 50 `.sst` files.
Am I missing something here? Is there a way to reclaim as much space as possible without deleting the files manually? 
Appreciate any help, thanks!

**Comment by pcmind** [comment]
At some point, compaction will reclaim space used. You can verify this by doing your test in a lop (10  times for instance), you won't be using 10 times the space at the end (all files in LevelDb are append only).

You can trigger manual compaction of the entire db by calling `db.compactRange(null, null)`

**Comment by wellington-felix-movile** [comment]
I misunderstood how leveldb works but it makes sense now. Anyway, calling `compactRange(null, null)` was enough to solve my problem. Thank you!
