### ISSUE TITLE
Apple notarization fails when referencing io.github.pcmind:leveldb 1.2. "The binary uses an SDK older than the 10.9 SDK."

### ISSUE THREAD

**Issue by devinvisible** [pcmind/leveldb#12]
During the Apple notarization process, stapler fails when I added a reference to leveldb 1.2 using the following definition in my pom.xml:
```
        <dependency>
            <groupId>io.github.pcmind</groupId>
            <artifactId>leveldb</artifactId>
            <classifier>uber</classifier>
            <version>1.2</version>
        </dependency>
```
The developer log states "Archive contains critical validation errors" and lists the follow issue:
```
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "myapp.pkg/output.pkg Contents/Payload/Library/Aternity/Agent/lib/leveldb-1.2-uber.jar/org/xerial/snappy/native/Mac/x86_64/libsnappyjava.jnilib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
```
I don't see libsnappyjava listed in this repo. Any idea where that came from? Do you know what the 10.9 SDK is in reference to?

**Comment by pcmind** [comment]
Dependency come from optional dependency: 
   ```
<dependency>
    <groupId>org.xerial.snappy</groupId>
    <artifactId>snappy-java</artifactId>
    <version>1.1.2.6 </version>
    <optional>true</optional>
</dependency>
```
This Snappy lib has a native implementation of Snappy compression algorithm, with an outdated Mac libsnappyjava.jnilib binary; even in newer lib version 1.1.7.6.

As this dependency is optional so it will be remove from uber jar a release a new version. In the mean time you can depend on non uber jar:
```
<dependency>
    <groupId>io.github.pcmind</groupId>
    <artifactId>leveldb</artifactId>
    <version>1.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by devinvisible** [comment]
The workaround was good. Thank you!

Any chance you can elaborate on what I miss out by not using the 'uber' classification?

**Comment by pcmind** [comment]
Th uber jar contains all dependencies required by the the lib inside the one jar. By not using the uber, your application is transitively depending on all dependencies of this lib and they must be provided separately.  

Leveldb can operate without Snappy compression and so snappy related libraries where already defined as optional, but where been included incorrectly in the jar.

See more on uber jar: https://stackoverflow.com/questions/11947037/what-is-an-uber-jar
