### ISSUE TITLE
Add hint to also add snappy dependency

### ISSUE THREAD

**Issue by mh-** [pcmind/leveldb#13]
Hi,

I'm not entirely sure if this problem is only specific to my use case, or just caused by my lack of experience with gradle vs. maven, but if not, maybe this helps others as well:

When opening a certain existing LevelDB, I get this exception:
`com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Attempt to invoke interface method 'int org.iq80.leveldb.util.Snappy$SPI.uncompress(java.nio.ByteBuffer, java.nio.ByteBuffer)' on a null object reference`

Debugging showed that `attempt` is `null` after
```
(from Snappy.java)
                else if ("iq80".equals(name.toLowerCase())) {
                    name = "org.iq80.leveldb.util.Snappy$IQ80Snappy";
                }
                attempt = (SPI) Thread.currentThread().getContextClassLoader().loadClass(name).newInstance();
```

This was the part I had added to gradle, based on your [maven recommendation](https://github.com/pcmind/leveldb/#adding-leveldb-to-your-build):
```
    implementation 'io.github.pcmind:leveldb:1.2'
```

If I add `snappy` as well, all works fine:
```
    implementation 'io.github.pcmind:leveldb:1.2'
    implementation 'org.iq80.snappy:snappy:0.4'
```

**Comment by pcmind** [comment]
`snappy` lib is optional so not included by default by dependency management, so if required, must be added to the user application dependency list. 

The following will be improve, to make it more clear:
* If `snappy` is required/used but missing, the exception should more helpful
* Update `readme` to document this behavior
