### ISSUE TITLE
awesome work for java leveldb

### ISSUE THREAD

**Issue by liukun4515** [pcmind/leveldb#5]
Hi, I found that you replied to my issue in dain/level.

I'm interested in leveldb and use the dain/leveldb, but some features of dain/leveldb are missing compare to leveldb(c++).

Can I join your work and add some feature to the leveldb of java?

**Comment by pcmind** [comment]
Of course, any help is welcome. Create an issue for what you would like to improve, we can discuss it and PR it. 
Right now I am finishing the reverse iterator feature for which I'll open a PR in the coming days. 
After which we should reach feature parity with original implementation. Non feature things are missing, like porting some tests (eg: fault injection test) and lot of things can be improved.

Thanks
