### ISSUE TITLE
write performance in concurrent mode

### ISSUE THREAD

**Issue by liukun4515** [pcmind/leveldb#6]
I bench the [leveldb c++](https://github.com/google/leveldb) using the db_bench and the benchmark in the ported of java.

I find the performance decrease with concurrent write.

The buffer_size and max_file_size just can improve a little performance.

**Comment by pcmind** [comment]
Do you mean that one implementation decrease in performance in concurrent write and the other not? 

Playing with those two values is expected to improve performance in both implementation.

Description is quite vague, could you elaborate on which tests where done, environment, expected/unexpected result etc.

**Comment by liukun4515** [comment]
> Do you mean that one implementation decrease in performance in concurrent write and the other not?
> 
> Playing with those two values is expected to improve performance in both implementation.
> 
> Description is quite vague, could you elaborate on which tests where done, environment, expected/unexpected result etc.

I bench the leveldb using the `db_bench`, below is the result.

```
 ./db_bench --benchmarks=fillrandom --threads=1
LevelDB:    version 1.20
Date:       Thu Mar  7 08:05:24 2019
CPU:        8 * Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
CPUCache:   8192 KB
Keys:       16 bytes each
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
------------------------------------------------
fillrandom   :       6.857 micros/op;   16.1 MB/s
```

```
./db_bench --benchmarks=fillrandom --threads=8
LevelDB:    version 1.20
Date:       Thu Mar  7 08:05:43 2019
CPU:        8 * Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
CPUCache:   8192 KB
Keys:       16 bytes each
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
------------------------------------------------
fillrandom   :      98.879 micros/op;    8.9 MB/s
```

Concurrent writes is slower than the single thread writes.

**Comment by pcmind** [comment]
Both Cpp and Java implementation are based on the same principal where writers are serialized(with some optimizations). I would not expect faster results in concurrent writes. 
But DB design is optimized for read, it permits concurrent read and do not need to wait for writes to complete.
