### ISSUE TITLE
ezdb tests failing with this leveldb implementation vs jni

### ISSUE THREAD

**Issue by subes** [pcmind/leveldb#8]
Hi, thanks a lot for your work put into this fork! Really appreciate the reverse iteration support here. Thus I have upgraded https://github.com/criccomini/ezdb to use this implementation.

Though the following tests are failing in the project ezdb-leveldb:
ezdb.leveldb.TestEzLevelDb.testVariationsOfDatasetNormal()
ezdb.leveldb.TestEzLevelDb.testVariationsOfDataset012()
ezdb.leveldb.TestEzLevelDb.testVariationsOfDataset01()
ezdb.leveldb.TestEzLevelDb.testVariationsOfDataset12()
ezdb.leveldb.TestEzLevelDb.testVariationsOfDataset210Reverse()
ezdb.leveldb.TestEzLevelDb.testVariationsOfDataset210()

While the same tests succeed in ezdb-leveldb-jni via:
ezdb.leveldb.TestEzLevelDbJni

**Comment by subes** [comment]
I will leave the master branch of ezdb for now at 1.0 of your fork. So you can debug it there.

**Comment by pcmind** [comment]
Nice it can help. 
There is an bug in [TestEzLevelDb#testVariationsOfDatasetNormal](https://github.com/criccomini/ezdb/blob/6381cb955349b38ebac25985c65662ffdc8fd6c2/ezdb-leveldb/src/test/java/ezdb/leveldb/TestEzLevelDb.java#L1260), that is the reason they are not failing in LevelDB JNI. `TestEzLevelDbJni` test class inherit from `TestEzLevelDb` but reflection method `getDeclaredMethods` will not return parent class methods. By replacing `getDeclaredMethods` to `getMethods` both test set will fail.

**Comment by subes** [comment]
You are right, it seems these test cases were always broken. Thanks for looking into it! I will remove the tests then as they are in fact badly designed.
